# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ azure-deploy ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    #- run: cp dist/mango-angular-frontend/index.html dist/mango-angular-frontend/404.html
    
    - name: Configure SSH
      run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
      env: 
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.AZURE_SSH_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}

    #- name: Stop service
    #  run: ssh staging "sudo systemctl stop mangofront"
      
    - name: Copy Release to Remote
      run: | 
          scp -r -i ~/.ssh/id_rsa ~/dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/dist/mango-angular-frontend
          scp -r -i ~/.ssh/id_rsa ~/dist/mango-angular-frontend/index.html ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/dist/mango-angular-frontend/404.html
      
    - name: Restart nginx
      run: ssh staging "sudo systemctl restart nginx"
