# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages CI/CD

on:
  push:
    branches: [ github-pages ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build-dev --if-present
      - run: cp dist/mango-angular-frontend/index.html dist/mango-angular-frontend/404.html

      - name: SSH-agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.GITPAGES_DEPLOY_KEY }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          repository-name: razumovskii/razumovskii.github.io
          ssh-key: true
          branch: master
          folder: dist/mango-angular-frontend
          clean: true
